version: '3'
services:
  db:
    image: postgres:12.0-alpine
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: bundle exec rails s -b 0.0.0.0
